### PR TITLE
Update LTS kernels to their latest version, and move to stable 4.16.

### PR DESCRIPTION
**Pull request by lmb**

### CODE REVIEW

**Comment by lmb** [comment]
Anything I can do to move this along?

**Comment by schu** [comment]
Hey @lmb thank you for the pull request and the ping!

I couldn't get the 4.16 ACI to work, the VM hangs. I tested with:

```
$ ./builder
...
$ sudo rkt run --debug --insecure-options=image --stage1-path=aci-files/stage1-kvm-1.29.0-linux-4.16.aci docker://alpine --exec=/bin/sh -- -c 'uname -r'
```

Does this work for you? I'm guessing it's due to some of the `VIRTIO` options not set for 4.16.

Trying again with:

```
$ rm aci-files/stage1-kvm-1.29.0-linux-4.16.aci
$ rm -rf build/*
$ cp config/linux-4.14.config config/linux-4.16.config
$ ./builder
### do necessary config (mostly pick defaults)
### copy used config back
$ cp build/4.16/kernel/source/.config config/linux-4.16.config
```

... the test from above works for me.

<details>
The diff to your commit is:

```
diff --git a/config/linux-4.16.config b/config/linux-4.16.config
index 405b990..5ced0e9 100644
--- a/config/linux-4.16.config
+++ b/config/linux-4.16.config
@@ -1,6 +1,6 @@
 #
 # Automatically generated file; DO NOT EDIT.
-# Linux/x86 4.16.5 Kernel Configuration
+# Linux/x86 4.16.0 Kernel Configuration
 #
 CONFIG_64BIT=y
 CONFIG_X86_64=y
@@ -391,6 +391,7 @@ CONFIG_EFI_PARTITION=y
 # CONFIG_CMDLINE_PARTITION is not set
 CONFIG_BLOCK_COMPAT=y
 CONFIG_BLK_MQ_PCI=y
+CONFIG_BLK_MQ_VIRTIO=y
 
 #
 # IO Schedulers
@@ -531,6 +532,8 @@ CONFIG_ARCH_DISCARD_MEMBLOCK=y
 # CONFIG_MEMORY_HOTPLUG is not set
 CONFIG_SPLIT_PTLOCK_CPUS=4
 CONFIG_ARCH_ENABLE_SPLIT_PMD_PTLOCK=y
+CONFIG_MEMORY_BALLOON=y
+# CONFIG_BALLOON_COMPACTION is not set
 CONFIG_COMPACTION=y
 CONFIG_MIGRATION=y
 CONFIG_ARCH_ENABLE_HUGEPAGE_MIGRATION=y
@@ -1108,6 +1111,8 @@ CONFIG_NET_SCH_FIFO=y
 # CONFIG_OPENVSWITCH is not set
 CONFIG_VSOCKETS=y
 CONFIG_VSOCKETS_DIAG=y
+CONFIG_VIRTIO_VSOCKETS=m
+CONFIG_VIRTIO_VSOCKETS_COMMON=m
 # CONFIG_NETLINK_DIAG is not set
 # CONFIG_MPLS is not set
 # CONFIG_NET_NSH is not set
@@ -1141,6 +1146,7 @@ CONFIG_STREAM_PARSER=y
 # CONFIG_WIMAX is not set
 # CONFIG_RFKILL is not set
 CONFIG_NET_9P=y
+CONFIG_NET_9P_VIRTIO=y
 # CONFIG_NET_9P_DEBUG is not set
 # CONFIG_CAIF is not set
 # CONFIG_CEPH_LIB is not set
@@ -1205,6 +1211,8 @@ CONFIG_BLK_DEV_RAM_COUNT=16
 CONFIG_BLK_DEV_RAM_SIZE=16384
 # CONFIG_CDROM_PKTCDVD is not set
 # CONFIG_ATA_OVER_ETH is not set
+CONFIG_VIRTIO_BLK=y
+# CONFIG_VIRTIO_BLK_SCSI is not set
 # CONFIG_BLK_DEV_RBD is not set
 # CONFIG_BLK_DEV_RSXX is not set
 
@@ -1357,6 +1365,7 @@ CONFIG_NET_CORE=y
 # CONFIG_TUN is not set
 # CONFIG_TUN_VNET_CROSS_LE is not set
 # CONFIG_VETH is not set
+CONFIG_VIRTIO_NET=y
 # CONFIG_NLMON is not set
 # CONFIG_ARCNET is not set
 
@@ -1484,12 +1493,15 @@ CONFIG_UNIX98_PTYS=y
 # CONFIG_SERIAL_RP2 is not set
 # CONFIG_SERIAL_FSL_LPUART is not set
 # CONFIG_SERIAL_DEV_BUS is not set
+CONFIG_HVC_DRIVER=y
+CONFIG_VIRTIO_CONSOLE=y
 # CONFIG_IPMI_HANDLER is not set
 CONFIG_HW_RANDOM=y
 # CONFIG_HW_RANDOM_TIMERIOMEM is not set
 CONFIG_HW_RANDOM_INTEL=y
 # CONFIG_HW_RANDOM_AMD is not set
 # CONFIG_HW_RANDOM_VIA is not set
+CONFIG_HW_RANDOM_VIRTIO=y
 CONFIG_NVRAM=m
 # CONFIG_R3964 is not set
 # CONFIG_APPLICOM is not set
@@ -1638,7 +1650,7 @@ CONFIG_HID_GENERIC=m
 # CONFIG_HID_WALTOP is not set
 # CONFIG_HID_GYRATION is not set
 # CONFIG_HID_ICADE is not set
-CONFIG_HID_ITE=y
+# CONFIG_HID_ITE is not set
 # CONFIG_HID_JABRA is not set
 # CONFIG_HID_TWINHAN is not set
 # CONFIG_HID_KENSINGTON is not set
@@ -1755,7 +1767,14 @@ CONFIG_RTC_DRV_CMOS=y
 # CONFIG_UIO is not set
 CONFIG_VIRT_DRIVERS=y
 # CONFIG_VBOXGUEST is not set
-# CONFIG_VIRTIO_MENU is not set
+CONFIG_VIRTIO=y
+CONFIG_VIRTIO_MENU=y
+CONFIG_VIRTIO_PCI=y
+CONFIG_VIRTIO_PCI_LEGACY=y
+CONFIG_VIRTIO_BALLOON=y
+CONFIG_VIRTIO_INPUT=y
+CONFIG_VIRTIO_MMIO=y
+CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES=y
 
 #
 # Microsoft Hyper-V guest support
@@ -2202,7 +2221,28 @@ CONFIG_FTRACE_MCOUNT_RECORD=y
 # CONFIG_TRACE_EVAL_MAP_FILE is not set
 # CONFIG_PROVIDE_OHCI1394_DMA_INIT is not set
 # CONFIG_DMA_API_DEBUG is not set
-# CONFIG_RUNTIME_TESTING_MENU is not set
+CONFIG_RUNTIME_TESTING_MENU=y
+# CONFIG_LKDTM is not set
+# CONFIG_TEST_LIST_SORT is not set
+# CONFIG_TEST_SORT is not set
+# CONFIG_ATOMIC64_SELFTEST is not set
+# CONFIG_TEST_HEXDUMP is not set
+# CONFIG_TEST_STRING_HELPERS is not set
+# CONFIG_TEST_KSTRTOX is not set
+# CONFIG_TEST_PRINTF is not set
+# CONFIG_TEST_BITMAP is not set
+# CONFIG_TEST_UUID is not set
+# CONFIG_TEST_RHASHTABLE is not set
+# CONFIG_TEST_HASH is not set
+# CONFIG_TEST_LKM is not set
+# CONFIG_TEST_USER_COPY is not set
+# CONFIG_TEST_BPF is not set
+# CONFIG_FIND_BIT_BENCHMARK is not set
+# CONFIG_TEST_FIRMWARE is not set
+# CONFIG_TEST_SYSCTL is not set
+# CONFIG_TEST_UDELAY is not set
+# CONFIG_TEST_STATIC_KEYS is not set
+# CONFIG_TEST_KMOD is not set
 # CONFIG_MEMTEST is not set
 # CONFIG_BUG_ON_DATA_CORRUPTION is not set
 # CONFIG_SAMPLES is not set
```
</details>

**Comment by schu** [comment]
Once the pull request is merged (and successfully build), all projects which use stage1-builder images have to be updated, since images are served from the CircleCI artifact store for the last successful build of master. We haven't got around to fix this yet (https://github.com/kinvolk/stage1-builder/issues/27). That's why we are slow with merging things here...

**Comment by schu** [comment]
@lmb if you want, you could also update rkt to [v1.30.0](https://github.com/rkt/rkt/releases/tag/v1.30.0)

**Comment by lmb** [comment]
Done. I haven't had the time to run this through tests yet.

I was going to suggest keeping the old versions, but with bumping rkt version that point is moot.

**Comment by schu** [comment]
https://github.com/kinvolk/stage1-builder/blob/master/builder#L51 also needs an update to 1.30.0

> I was going to suggest keeping the old versions, but with bumping rkt version that point is moot.

I'll see to get to work on #27 soon. It's a pain as is.

**Comment by lmb** [comment]
Done.

**Pull request merged**
