### PR TITLE
Allow parameterized builds

### PR DESCRIPTION
**Pull request by schu**
Check for set `S1B_KERNEL_VERSION` and only fallback to default.

### CODE REVIEW

**Comment by schu** [comment]
Allows us to trigger builds with e.g.

```
cat <<EOF | curl -sSL -H "Content-Type: application/json" -d @- "https://circleci.com/api/v1.1/project/github/kinvolk/stage1-builder/tree/master?circle-token=${api_token}"
{
  "build_parameters": {
    "S1B_KERNEL_VERSION": "$1"
  }
}
EOF
```

**Comment by iaguis** [comment]
Is it too crazy to make it work for a list of versions?

**Comment by schu** [comment]
Tested manually with `--stage1-name=kinvolk.io/aci/rkt/stage1-kvm:1.23.0,kernelversion=4.9.9`, works.

> Is it too crazy to make it work for a list of versions?

Not crazy I think :) But would love to merge this as is and do it in a later PR. (Since I need it to test automatically triggered builds when a new kernel was released..)

**Comment by iaguis** [comment]
lgtm

**Pull request merged**
