### PR TITLE
config: add linux 4.15

### PR DESCRIPTION
**Pull request by iaguis**
Also, update the rkt used to v1.29.0

### CODE REVIEW

**Comment by iaguis** [comment]
Build passed but I cancelled it because I started it with SSH: https://circleci.com/gh/kinvolk/stage1-builder/111

**Comment by schu** [comment]
https://github.com/weaveworks/tcptracer-bpf/blob/master/semaphore.sh#L22 and https://github.com/iovisor/gobpf/blob/master/semaphore.sh#L13 currently use `4.4.45`, `4.9.6` and `4.10.6`. Previously, I triggered a manual build after updates to master to make sure the images are in the artifact store again. I can do that here as well or..

..we instead drop `4.1.38` and `4.8.13` and update the other LTS kernels to their latest patch release + update tcptracer-bpf and gobpf to use those.

Also, I'm not sure if mixing an older rkt with a newer stage1 does work? If not, that would need to be updated as well.

**Comment by iaguis** [comment]
> ..we instead drop 4.1.38 and 4.8.13 and update the other LTS kernels to their latest patch release + update tcptracer-bpf and gobpf to use those.

I'll do that.

> Also, I'm not sure if mixing an older rkt with a newer stage1 does work? If not, that would need to be updated as well.

This shouldn't be a problem but I'll update it too just in case.

**Comment by iaguis** [comment]
After this PR we'll have kernels:

* 4.1.49
* 4.4.114
* 4.9.79 
* 4.14.16
* 4.15 (current release)

I kept 4.1 because it's a longterm release too and we already have a config for it, but I can remove it if you want.

Once this is merged, I'll file PRs updating gobpf and tcptracer-bpf.

**Comment by schu** [comment]
AFAIK `4.1.49` is not used by anybody, therefore I would rather remove it to save a bit of build time. But we can also do that in a later update.

**Pull request merged**
